load('ext://pack', 'pack')

# OS Identification
gradlew = "./gradlew"
expected_ref = "$EXPECTED_REF"
if os.name == "nt":
  gradlew = "gradlew.bat"
  expected_ref = "%EXPECTED_REF%"

# Build
pack(
    '${{values.artifact_id}}',
    deps=['build.gradle', './build/classes'],
    live_update = [
        sync('./bin/main', '/workspace/BOOT-INF/classes'),
    ],
)

# Deploy
k8s_yaml(kustomize('k8s'))

# Manage
k8s_resource('${{values.artifact_id}}', port_forwards=['${{values.port}}:${{values.port}}'])

local_resource(
    './record-start-time.sh',
)