apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{values.artifact_id}}
  labels:
    app: ${{values.artifact_id}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{values.artifact_id}}
  template:
    metadata:
      labels:
        app: ${{values.artifact_id}}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "${{values.port}}"
    spec:
      containers:
        - name: ${{values.artifact_id}}
          image: ${{values.artifact_id}}
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: ${{values.port}}