name: Acceptance Stage
on:
  workflow_run:
    workflows: [ 'Commit Stage' ]
    types: [ completed ]
    branches: main
concurrency: acceptance

permissions:
  issues: write

jobs:
  prepare:
      runs-on: ubuntu-22.04
      name: Checkout source code
      steps:
        - name: Retrieve Version
          run: |
            echo "::set-output name=VERSION_NAME::$(${{github.workspace}}/gradlew -q printVersionName)"
          id: app_version
        - name: Get version
          run: |
            echo "version_name=${{steps.android_version.outputs.VERSION_NAME}}" >> $GITHUB_ENV
  functional:
    name: Functional Acceptance Tests
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-22.04
    steps:
      - run: echo "Running functional acceptance tests"
  performance:
    name: Performance Tests
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-22.04
    steps:
      - run: echo "Running performance tests"
  security:
    name: Security Tests
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-22.04
    steps:
      - run: echo "Running security tests"

  approval:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Wait for approval
        uses: trstringer/manual-approval@v1
        timeout-minutes: 60
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          minimum-approvals: 1
          approvers: ${{ github.repository_owner }}
          issue-title: "🚀 Deploying v${{env.version_name}} to prod from staging"
          issue-body: "Please approve or deny the deployment of version v${{env.version_name}}."
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: ''
          additional-denied-words: ''